export type PackageDependencyType = "dependencies" | "devDependencies" | "peerDependencies"
export type PackageVersionPolicy = "caret" | "exact"

export type PackageVersionInfo = {
  name: string
  version: string
  range: string
  policy: PackageVersionPolicy
  dependencyType: PackageDependencyType
  notes?: string
}

export const PACKAGE_VERSION_POLICY = {
  policy: "caret",
  generatedWithPackageVersionsAt: "2026-07-06",
  source: "npm view <package> version",
} as const

export const MVP_PACKAGE_NAMES = [
  "@base-ui/react",
  "@dnd-kit/core",
  "@dnd-kit/modifiers",
  "@dnd-kit/sortable",
  "@fullcalendar/react",
  "@hookform/resolvers",
  "@shadcn/react",
  "@tailwindcss/vite",
  "@tanstack/react-table",
  "@types/react",
  "@types/react-dom",
  "@types/topojson-client",
  "@vitejs/plugin-react",
  "axios",
  "class-variance-authority",
  "clsx",
  "cmdk",
  "d3-geo",
  "date-fns",
  "embla-carousel-react",
  "input-otp",
  "lucide-react",
  "radix-ui",
  "react",
  "react-day-picker",
  "react-dom",
  "react-hook-form",
  "react-resizable-panels",
  "react-router-dom",
  "recharts",
  "simple-icons",
  "sonner",
  "tailwind-merge",
  "tailwindcss",
  "topojson-client",
  "tw-animate-css",
  "typescript",
  "vaul",
  "vite",
  "zod",
  "zustand",
] as const

export type KnownPackageName = (typeof MVP_PACKAGE_NAMES)[number]

export const packageVersions = {
  "@base-ui/react": {
    name: "@base-ui/react",
    version: "1.6.0",
    range: "^1.6.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@dnd-kit/core": {
    name: "@dnd-kit/core",
    version: "6.3.1",
    range: "^6.3.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@dnd-kit/modifiers": {
    name: "@dnd-kit/modifiers",
    version: "9.0.0",
    range: "^9.0.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@dnd-kit/sortable": {
    name: "@dnd-kit/sortable",
    version: "10.0.0",
    range: "^10.0.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@fullcalendar/react": {
    name: "@fullcalendar/react",
    version: "7.0.0",
    range: "^7.0.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@hookform/resolvers": {
    name: "@hookform/resolvers",
    version: "5.4.0",
    range: "^5.4.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@shadcn/react": {
    name: "@shadcn/react",
    version: "0.1.0",
    range: "^0.1.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@tailwindcss/vite": {
    name: "@tailwindcss/vite",
    version: "4.3.2",
    range: "^4.3.2",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  "@tanstack/react-table": {
    name: "@tanstack/react-table",
    version: "8.21.3",
    range: "^8.21.3",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "@types/react": {
    name: "@types/react",
    version: "19.2.17",
    range: "^19.2.17",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  "@types/react-dom": {
    name: "@types/react-dom",
    version: "19.2.3",
    range: "^19.2.3",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  "@types/topojson-client": {
    name: "@types/topojson-client",
    version: "3.1.5",
    range: "^3.1.5",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  "@vitejs/plugin-react": {
    name: "@vitejs/plugin-react",
    version: "6.0.3",
    range: "^6.0.3",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  axios: {
    name: "axios",
    version: "1.18.1",
    range: "^1.18.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "class-variance-authority": {
    name: "class-variance-authority",
    version: "0.7.1",
    range: "^0.7.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  clsx: {
    name: "clsx",
    version: "2.1.1",
    range: "^2.1.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  cmdk: {
    name: "cmdk",
    version: "1.1.1",
    range: "^1.1.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "d3-geo": {
    name: "d3-geo",
    version: "3.1.1",
    range: "^3.1.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "date-fns": {
    name: "date-fns",
    version: "4.4.0",
    range: "^4.4.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "embla-carousel-react": {
    name: "embla-carousel-react",
    version: "8.6.0",
    range: "^8.6.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "input-otp": {
    name: "input-otp",
    version: "1.4.2",
    range: "^1.4.2",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "lucide-react": {
    name: "lucide-react",
    version: "1.23.0",
    range: "^1.23.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "radix-ui": {
    name: "radix-ui",
    version: "1.6.1",
    range: "^1.6.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  react: {
    name: "react",
    version: "19.2.7",
    range: "^19.2.7",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "react-day-picker": {
    name: "react-day-picker",
    version: "10.0.1",
    range: "^10.0.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "react-dom": {
    name: "react-dom",
    version: "19.2.7",
    range: "^19.2.7",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "react-hook-form": {
    name: "react-hook-form",
    version: "7.81.0",
    range: "^7.81.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "react-resizable-panels": {
    name: "react-resizable-panels",
    version: "4.12.1",
    range: "^4.12.1",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "react-router-dom": {
    name: "react-router-dom",
    version: "7.11.0",
    range: "^7.11.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  recharts: {
    name: "recharts",
    version: "3.8.0",
    range: "^3.8.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "simple-icons": {
    name: "simple-icons",
    version: "16.25.0",
    range: "^16.25.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  sonner: {
    name: "sonner",
    version: "2.0.7",
    range: "^2.0.7",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "tailwind-merge": {
    name: "tailwind-merge",
    version: "3.6.0",
    range: "^3.6.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  tailwindcss: {
    name: "tailwindcss",
    version: "4.3.2",
    range: "^4.3.2",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  "topojson-client": {
    name: "topojson-client",
    version: "3.1.0",
    range: "^3.1.0",
    policy: "caret",
    dependencyType: "dependencies",
  },
  "tw-animate-css": {
    name: "tw-animate-css",
    version: "1.4.0",
    range: "^1.4.0",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  typescript: {
    name: "typescript",
    version: "6.0.3",
    range: "^6.0.3",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  vaul: {
    name: "vaul",
    version: "1.1.2",
    range: "^1.1.2",
    policy: "caret",
    dependencyType: "dependencies",
  },
  vite: {
    name: "vite",
    version: "8.1.3",
    range: "^8.1.3",
    policy: "caret",
    dependencyType: "devDependencies",
  },
  zod: {
    name: "zod",
    version: "4.4.3",
    range: "^4.4.3",
    policy: "caret",
    dependencyType: "dependencies",
  },
  zustand: {
    name: "zustand",
    version: "5.0.14",
    range: "^5.0.14",
    policy: "caret",
    dependencyType: "dependencies",
  },
} satisfies Record<KnownPackageName, PackageVersionInfo>

export function packageRange(packageName: KnownPackageName): string {
  return packageVersions[packageName].range
}
