changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies and maintenance
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
