import path from "node:path"

import type { FileMapping, ResolveConflict } from "@dittojs/core"

import { createDittoMetadata } from "./metadata"
import { createPackageJson } from "./package-json"
import {
  METADATA_TARGET,
  PACKAGE_JSON_TARGET,
  README_TARGET,
  normalizeSafeRelativePath,
  resolveOutputDir,
  resolveSafeOutputPath,
} from "./paths"
import { createReadme } from "./readme"
import {
  requireProjectStructureAdapter,
  resolveStructurePath,
  selectedProjectStructureAdapter,
  type ProjectStructureAdapter,
} from "./structure"
import type { GenerateProjectInput, GenerateProjectResult, GeneratorWarning } from "./types"
import { GenerateProjectError } from "./types"
import { copyTemplateFile, writeJsonFile, writeTextFile } from "./writer"

const RESERVED_GENERATED_TARGETS = new Set([PACKAGE_JSON_TARGET, METADATA_TARGET, README_TARGET])

type ResolvedFileMapping = {
  from: string
  to: string
  slot?: string
  name?: string
  route?: string
  importToken?: string
  importSpecifier?: string
}

function summarizeResolverErrors(conflicts: ResolveConflict[]): string {
  return conflicts.map((conflict) => conflict.message).join("; ")
}

function warningFromRecipeWarning(warning: { message: string; reason?: string }): GeneratorWarning {
  const generatorWarning: GeneratorWarning = {
    message: warning.message,
  }

  if (warning.reason !== undefined) {
    generatorWarning.reason = warning.reason
  }

  return generatorWarning
}

function validateRecipeCanGenerate(input: GenerateProjectInput): void {
  const errorConflicts = input.resolvedRecipe.conflicts.filter(
    (conflict) => conflict.severity === "error",
  )

  if (errorConflicts.length > 0) {
    throw new GenerateProjectError(
      `Cannot generate project with resolver errors: ${summarizeResolverErrors(errorConflicts)}`,
    )
  }
}

function hasStringProperty(file: FileMapping, key: string): boolean {
  const value = (file as Record<string, unknown>)[key]

  return typeof value === "string" && value.trim().length > 0
}

function usesStructureSlot(file: FileMapping): boolean {
  return hasStringProperty(file, "slot")
}

function trimCharacter(value: string, character: string): string {
  let start = 0
  let end = value.length

  while (value[start] === character) start += 1
  while (end > start && value[end - 1] === character) end -= 1

  return value.slice(start, end)
}

function importToken(slot: string, name: string): string {
  const tokenBody = trimCharacter(
    `${slot}_${name}`.replace(/[^A-Za-z0-9]+/g, "_"),
    "_",
  ).toUpperCase()

  return `__DITTO_IMPORT_${tokenBody}__`
}

function importSpecifier(
  targetPath: string,
  adapter: ProjectStructureAdapter | undefined,
): string | undefined {
  if (adapter === undefined) {
    return undefined
  }

  const sourcePrefix = `${adapter.sourceRoot}/`

  if (!targetPath.startsWith(sourcePrefix)) {
    return undefined
  }

  const sourceRelativePath = targetPath.slice(sourcePrefix.length).replace(/\.(tsx|ts|jsx|js)$/, "")

  return `${adapter.importAlias}/${sourceRelativePath}`
}

function resolveFileMappingTarget(
  file: FileMapping,
  adapter: ProjectStructureAdapter | undefined,
): string {
  const hasDirectTarget = hasStringProperty(file, "to")
  const hasSlotTarget = hasStringProperty(file, "slot")

  if (hasDirectTarget && hasSlotTarget) {
    throw new GenerateProjectError(
      `File mapping "${file.from}" must use either to or slot, not both.`,
    )
  }

  if (!hasDirectTarget && !hasSlotTarget) {
    throw new GenerateProjectError(`File mapping "${file.from}" must include either to or slot.`)
  }

  if (hasDirectTarget) {
    return normalizeSafeRelativePath((file as { to: string }).to, "output target")
  }

  if (adapter === undefined) {
    throw new GenerateProjectError(
      `File mapping "${file.from}" uses slot "${(file as { slot?: string }).slot}" without a selected project structure.`,
    )
  }

  const slotFile = file as {
    slot: string
    name?: string
    feature?: string
    route?: string
  }

  return resolveStructurePath({
    adapter,
    slot: slotFile.slot,
    name: slotFile.name,
    feature: slotFile.feature,
    route: slotFile.route,
  })
}

function resolveFileMappings(
  files: FileMapping[],
  adapter: ProjectStructureAdapter | undefined,
): ResolvedFileMapping[] {
  const targets = new Map<string, ResolvedFileMapping>()
  const resolvedFiles: ResolvedFileMapping[] = []

  for (const file of files) {
    normalizeSafeRelativePath(file.from, "template source")

    const targetPath = resolveFileMappingTarget(file, adapter)

    if (RESERVED_GENERATED_TARGETS.has(targetPath)) {
      throw new GenerateProjectError(
        `File target collision at "${targetPath}": this path is generated by DittoJs.`,
      )
    }

    const existing = targets.get(targetPath)

    if (existing !== undefined) {
      throw new GenerateProjectError(
        `File target collision at "${targetPath}": "${existing.from}" and "${file.from}" share the same output target.`,
      )
    }

    const resolvedFile: ResolvedFileMapping = {
      from: file.from,
      to: targetPath,
    }
    const slotFile = file as { slot?: string; name?: string }

    if (
      slotFile.slot !== undefined &&
      slotFile.name !== undefined &&
      slotFile.name.trim().length > 0
    ) {
      resolvedFile.importToken = importToken(slotFile.slot, slotFile.name)
      const specifier = importSpecifier(targetPath, adapter)

      if (specifier !== undefined) {
        resolvedFile.importSpecifier = specifier
      }
    }

    if (slotFile.slot !== undefined) {
      resolvedFile.slot = slotFile.slot
    }

    if (slotFile.name !== undefined) {
      resolvedFile.name = slotFile.name
    }

    const route = (file as { route?: string }).route

    if (route !== undefined) {
      resolvedFile.route = route
    }

    targets.set(targetPath, resolvedFile)
    resolvedFiles.push(resolvedFile)
  }

  return resolvedFiles
}

function importReplacements(resolvedFiles: ResolvedFileMapping[]): Record<string, string> {
  return Object.fromEntries(
    resolvedFiles
      .filter(
        (file): file is ResolvedFileMapping & { importToken: string; importSpecifier: string } =>
          file.importToken !== undefined && file.importSpecifier !== undefined,
      )
      .map((file) => [file.importToken, file.importSpecifier]),
  )
}

function projectName(input: GenerateProjectInput, outputDir: string): string {
  return input.projectName?.trim() || path.basename(outputDir) || "ditto-generated-project"
}

function routeIdentifier(route: string, index: number): string {
  const identifier = route
    .replace(/[^A-Za-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")

  return `${identifier || "Index"}Page${index + 1}`
}

function routePath(route: string): string {
  const trimmed = trimCharacter(route.trim(), "/")

  return trimmed.length === 0 ? "/" : `/${trimmed}`
}

function createReactRouterFile(resolvedFiles: ResolvedFileMapping[]): string {
  const pageFiles = resolvedFiles.filter(
    (
      file,
    ): file is ResolvedFileMapping & {
      importSpecifier: string
      route: string
    } => file.slot === "page" && file.importSpecifier !== undefined && file.route !== undefined,
  )

  const imports = pageFiles
    .map(
      (file, index) =>
        `import ${routeIdentifier(file.route, index)} from "${file.importSpecifier}"`,
    )
    .join("\n")
  const routes =
    pageFiles.length === 0
      ? '  { path: "/", element: <App /> },'
      : pageFiles
          .map(
            (file, index) =>
              `  { path: ${JSON.stringify(routePath(file.route))}, element: <${routeIdentifier(
                file.route,
                index,
              )} /> },`,
          )
          .join("\n")

  return `import { createBrowserRouter, RouterProvider } from "react-router-dom"
${pageFiles.length === 0 ? 'import { App } from "@/App"' : imports}

export const router = createBrowserRouter([
${routes}
])

export function AppRouter() {
  return <RouterProvider router={router} />
}
`
}

function includesReactRouter(resolvedRecipe: GenerateProjectInput["resolvedRecipe"]): boolean {
  return resolvedRecipe.effectiveSelections.includes("routing.react-router")
}

export async function generateProject(input: GenerateProjectInput): Promise<GenerateProjectResult> {
  validateRecipeCanGenerate(input)
  const usesSlots = input.resolvedRecipe.files.some(usesStructureSlot)
  const adapter = usesSlots
    ? requireProjectStructureAdapter(input.resolvedRecipe)
    : selectedProjectStructureAdapter(input.resolvedRecipe)
  const resolvedFiles = resolveFileMappings(input.resolvedRecipe.files, adapter)
  const replacements = importReplacements(resolvedFiles)

  if (
    input.resolvedRecipe.files.length > 0 &&
    (input.templateRoot === undefined || input.templateRoot.trim().length === 0)
  ) {
    throw new GenerateProjectError(
      "templateRoot is required when resolvedRecipe.files contains file mappings.",
    )
  }

  const outputDir = resolveOutputDir(input.outputDir)
  const filesWritten: string[] = []
  const packageManager = input.packageManager ?? "pnpm"
  const displayProjectName = projectName(input, outputDir)

  await writeJsonFile({
    outputDir,
    targetPath: PACKAGE_JSON_TARGET,
    value: createPackageJson({
      packages: input.resolvedRecipe.packages,
      outputDir,
      projectName: input.projectName,
    }),
  }).then((filePath) => filesWritten.push(filePath))

  await writeJsonFile({
    outputDir,
    targetPath: METADATA_TARGET,
    value: createDittoMetadata({
      ...input,
      selectedProjectStructure: adapter?.id,
    }),
  }).then((filePath) => filesWritten.push(filePath))

  await writeTextFile({
    outputDir,
    targetPath: README_TARGET,
    contents: createReadme({
      projectName: displayProjectName,
      packageManager,
      resolvedRecipe: input.resolvedRecipe,
    }),
  }).then((filePath) => filesWritten.push(filePath))

  for (const file of resolvedFiles) {
    filesWritten.push(
      await copyTemplateFile({
        templateRoot: input.templateRoot ?? "",
        outputDir,
        file,
        replacements,
      }),
    )
  }

  if (includesReactRouter(input.resolvedRecipe)) {
    filesWritten.push(
      await writeTextFile({
        outputDir,
        targetPath: "src/app/router.tsx",
        contents: createReactRouterFile(resolvedFiles),
      }),
    )
  }

  return {
    outputDir,
    filesWritten,
    packageJsonPath: resolveSafeOutputPath(outputDir, PACKAGE_JSON_TARGET).absolutePath,
    metadataPath: resolveSafeOutputPath(outputDir, METADATA_TARGET).absolutePath,
    readmePath: resolveSafeOutputPath(outputDir, README_TARGET).absolutePath,
    warnings: input.resolvedRecipe.warnings.map(warningFromRecipeWarning),
  }
}
