import path from "node:path"

import type { FileMapping, ResolveConflict } from "@dittojs/core"

import { createDittoMetadata } from "./metadata"
import { createPackageJson } from "./package-json"
import {
  METADATA_TARGET,
  PACKAGE_JSON_TARGET,
  README_TARGET,
  normalizeSafeRelativePath,
  resolveOutputDir,
  resolveSafeOutputPath,
} from "./paths"
import { createReadme } from "./readme"
import {
  requireProjectStructureAdapter,
  resolveStructurePath,
  selectedProjectStructureAdapter,
  type ProjectStructureAdapter,
} from "./structure"
import type { GenerateProjectInput, GenerateProjectResult, GeneratorWarning } from "./types"
import { GenerateProjectError } from "./types"
import { copyTemplateFile, writeJsonFile, writeTextFile } from "./writer"

const RESERVED_GENERATED_TARGETS = new Set([PACKAGE_JSON_TARGET, METADATA_TARGET, README_TARGET])

type ResolvedFileMapping = {
  from: string
  to: string
}

function summarizeResolverErrors(conflicts: ResolveConflict[]): string {
  return conflicts.map((conflict) => conflict.message).join("; ")
}

function warningFromRecipeWarning(warning: { message: string; reason?: string }): GeneratorWarning {
  const generatorWarning: GeneratorWarning = {
    message: warning.message,
  }

  if (warning.reason !== undefined) {
    generatorWarning.reason = warning.reason
  }

  return generatorWarning
}

function validateRecipeCanGenerate(input: GenerateProjectInput): void {
  const errorConflicts = input.resolvedRecipe.conflicts.filter(
    (conflict) => conflict.severity === "error",
  )

  if (errorConflicts.length > 0) {
    throw new GenerateProjectError(
      `Cannot generate project with resolver errors: ${summarizeResolverErrors(errorConflicts)}`,
    )
  }
}

function hasStringProperty(file: FileMapping, key: string): boolean {
  const value = (file as Record<string, unknown>)[key]

  return typeof value === "string" && value.trim().length > 0
}

function usesStructureSlot(file: FileMapping): boolean {
  return hasStringProperty(file, "slot")
}

function resolveFileMappingTarget(
  file: FileMapping,
  adapter: ProjectStructureAdapter | undefined,
): string {
  const hasDirectTarget = hasStringProperty(file, "to")
  const hasSlotTarget = hasStringProperty(file, "slot")

  if (hasDirectTarget && hasSlotTarget) {
    throw new GenerateProjectError(
      `File mapping "${file.from}" must use either to or slot, not both.`,
    )
  }

  if (!hasDirectTarget && !hasSlotTarget) {
    throw new GenerateProjectError(`File mapping "${file.from}" must include either to or slot.`)
  }

  if (hasDirectTarget) {
    return normalizeSafeRelativePath((file as { to: string }).to, "output target")
  }

  if (adapter === undefined) {
    throw new GenerateProjectError(
      `File mapping "${file.from}" uses slot "${(file as { slot?: string }).slot}" without a selected project structure.`,
    )
  }

  const slotFile = file as {
    slot: string
    name?: string
    feature?: string
    route?: string
  }

  return resolveStructurePath({
    adapter,
    slot: slotFile.slot,
    name: slotFile.name,
    feature: slotFile.feature,
    route: slotFile.route,
  })
}

function resolveFileMappings(
  files: FileMapping[],
  adapter: ProjectStructureAdapter | undefined,
): ResolvedFileMapping[] {
  const targets = new Map<string, ResolvedFileMapping>()
  const resolvedFiles: ResolvedFileMapping[] = []

  for (const file of files) {
    normalizeSafeRelativePath(file.from, "template source")

    const targetPath = resolveFileMappingTarget(file, adapter)

    if (RESERVED_GENERATED_TARGETS.has(targetPath)) {
      throw new GenerateProjectError(
        `File target collision at "${targetPath}": this path is generated by DittoJs.`,
      )
    }

    const existing = targets.get(targetPath)

    if (existing !== undefined) {
      throw new GenerateProjectError(
        `File target collision at "${targetPath}": "${existing.from}" and "${file.from}" share the same output target.`,
      )
    }

    const resolvedFile: ResolvedFileMapping = {
      from: file.from,
      to: targetPath,
    }

    targets.set(targetPath, resolvedFile)
    resolvedFiles.push(resolvedFile)
  }

  return resolvedFiles
}

function projectName(input: GenerateProjectInput, outputDir: string): string {
  return input.projectName?.trim() || path.basename(outputDir) || "ditto-generated-project"
}

export async function generateProject(input: GenerateProjectInput): Promise<GenerateProjectResult> {
  validateRecipeCanGenerate(input)
  const usesSlots = input.resolvedRecipe.files.some(usesStructureSlot)
  const adapter = usesSlots
    ? requireProjectStructureAdapter(input.resolvedRecipe)
    : selectedProjectStructureAdapter(input.resolvedRecipe)
  const resolvedFiles = resolveFileMappings(input.resolvedRecipe.files, adapter)

  if (
    input.resolvedRecipe.files.length > 0 &&
    (input.templateRoot === undefined || input.templateRoot.trim().length === 0)
  ) {
    throw new GenerateProjectError(
      "templateRoot is required when resolvedRecipe.files contains file mappings.",
    )
  }

  const outputDir = resolveOutputDir(input.outputDir)
  const filesWritten: string[] = []
  const packageManager = input.packageManager ?? "pnpm"
  const displayProjectName = projectName(input, outputDir)

  await writeJsonFile({
    outputDir,
    targetPath: PACKAGE_JSON_TARGET,
    value: createPackageJson({
      packages: input.resolvedRecipe.packages,
      outputDir,
      projectName: input.projectName,
    }),
  }).then((filePath) => filesWritten.push(filePath))

  await writeJsonFile({
    outputDir,
    targetPath: METADATA_TARGET,
    value: createDittoMetadata({
      ...input,
      selectedProjectStructure: adapter?.id,
    }),
  }).then((filePath) => filesWritten.push(filePath))

  await writeTextFile({
    outputDir,
    targetPath: README_TARGET,
    contents: createReadme({
      projectName: displayProjectName,
      packageManager,
      resolvedRecipe: input.resolvedRecipe,
    }),
  }).then((filePath) => filesWritten.push(filePath))

  for (const file of resolvedFiles) {
    filesWritten.push(
      await copyTemplateFile({
        templateRoot: input.templateRoot ?? "",
        outputDir,
        file,
      }),
    )
  }

  return {
    outputDir,
    filesWritten,
    packageJsonPath: resolveSafeOutputPath(outputDir, PACKAGE_JSON_TARGET).absolutePath,
    metadataPath: resolveSafeOutputPath(outputDir, METADATA_TARGET).absolutePath,
    readmePath: resolveSafeOutputPath(outputDir, README_TARGET).absolutePath,
    warnings: input.resolvedRecipe.warnings.map(warningFromRecipeWarning),
  }
}
