import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import path from "node:path"

import { afterEach, describe, expect, it } from "vitest"

import type { ResolvedRecipe } from "@dittojs/core"

import { generateProject } from "./index"

const createdAt = "2026-07-05T00:00:00.000Z"
const tempDirs: string[] = []

function resolvedRecipe(overrides: Partial<ResolvedRecipe> = {}): ResolvedRecipe {
  return {
    userSelections: ["framework.react"],
    effectiveSelections: ["framework.react"],
    selectionReasons: {
      "framework.react": [{ type: "user" }],
    },
    locks: {},
    conflicts: [],
    warnings: [],
    packages: {
      dependencies: {
        react: "latest",
      },
      devDependencies: {
        typescript: "latest",
        vite: "latest",
      },
      peerDependencies: {},
    },
    files: [],
    defaultsApplied: [],
    metadata: {
      resolvedAt: createdAt,
    },
    ...overrides,
  }
}

async function createTempDir(label: string): Promise<string> {
  const tempDir = await mkTemp(path.join(tmpdir(), `ditto-generator-${label}-`))
  tempDirs.push(tempDir)

  return tempDir
}

async function mkTemp(prefix: string): Promise<string> {
  const { mkdtemp } = await import("node:fs/promises")

  return mkdtemp(prefix)
}

async function readJson<T>(filePath: string): Promise<T> {
  return JSON.parse(await readFile(filePath, "utf8")) as T
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await stat(filePath)
    return true
  } catch {
    return false
  }
}

afterEach(async () => {
  await Promise.all(
    tempDirs.splice(0).map((tempDir) => rm(tempDir, { recursive: true, force: true })),
  )
})

describe("generateProject", () => {
  it("writes package.json from resolved packages", async () => {
    const outputDir = await createTempDir("package-json")
    const result = await generateProject({
      resolvedRecipe: resolvedRecipe(),
      outputDir,
      projectName: "Test App",
      createdAt,
    })
    const packageJson = await readJson<{
      name: string
      scripts: Record<string, string>
      dependencies: Record<string, string>
      devDependencies: Record<string, string>
    }>(path.join(outputDir, "package.json"))

    expect(result.filesWritten).toContain("package.json")
    expect(packageJson).toMatchObject({
      name: "test-app",
      scripts: {
        dev: "vite",
        build: "tsc -b && vite build",
        preview: "vite preview",
        typecheck: "tsc --noEmit",
      },
      dependencies: {
        react: "latest",
      },
      devDependencies: {
        typescript: "latest",
        vite: "latest",
      },
    })
  })

  it("writes ditto.generated.json metadata", async () => {
    const outputDir = await createTempDir("metadata")

    await generateProject({
      resolvedRecipe: resolvedRecipe({
        userSelections: ["preset.custom"],
        effectiveSelections: ["preset.custom", "framework.react"],
        metadata: {
          resolvedAt: createdAt,
          preset: "preset.custom",
        },
      }),
      outputDir,
      generatorVersion: "test-version",
      createdAt,
    })

    await expect(readJson(path.join(outputDir, "ditto.generated.json"))).resolves.toMatchObject({
      generator: "dittojs",
      generatorPackage: "@dittojs/generator",
      generatorVersion: "test-version",
      createdAt,
      preset: "preset.custom",
      userSelections: ["preset.custom"],
      effectiveSelections: ["preset.custom", "framework.react"],
      packages: {
        dependencies: {
          react: "latest",
        },
      },
    })
  })

  it("writes README.md with stack and commands", async () => {
    const outputDir = await createTempDir("readme")

    await generateProject({
      resolvedRecipe: resolvedRecipe({
        effectiveSelections: ["framework.react", "tooling.vite", "styling.tailwind"],
      }),
      outputDir,
      projectName: "Readme App",
      createdAt,
    })

    const readme = await readFile(path.join(outputDir, "README.md"), "utf8")

    expect(readme).toContain("# Readme App")
    expect(readme).toContain("Generated by DittoJs.")
    expect(readme).toContain("## Stack Summary")
    expect(readme).toContain("- framework.react")
    expect(readme).toContain("pnpm install")
    expect(readme).toContain("pnpm dev")
    expect(readme).toContain("pnpm build")
  })

  it("rejects unsafe target paths", async () => {
    const outputDir = await createTempDir("unsafe-target")

    await expect(
      generateProject({
        resolvedRecipe: resolvedRecipe({
          files: [
            {
              from: "safe.txt",
              to: "../outside.txt",
            },
          ],
        }),
        outputDir,
        templateRoot: outputDir,
        createdAt,
      }),
    ).rejects.toThrow(/Unsafe output target path/)

    await expect(
      generateProject({
        resolvedRecipe: resolvedRecipe({
          files: [
            {
              from: "safe.txt",
              to: "/absolute.txt",
            },
          ],
        }),
        outputDir,
        templateRoot: outputDir,
        createdAt,
      }),
    ).rejects.toThrow(/absolute paths are not allowed/)
  })

  it("detects file collisions in resolved file mappings", async () => {
    const outputDir = await createTempDir("collisions")

    await expect(
      generateProject({
        resolvedRecipe: resolvedRecipe({
          files: [
            {
              from: "alpha.txt",
              to: "src/shared.txt",
            },
            {
              from: "beta.txt",
              to: "src/shared.txt",
            },
          ],
        }),
        outputDir,
        templateRoot: outputDir,
        createdAt,
      }),
    ).rejects.toThrow(/File target collision/)
  })

  it("respects resolver error conflicts", async () => {
    const outputDir = await createTempDir("resolver-conflicts")

    await expect(
      generateProject({
        resolvedRecipe: resolvedRecipe({
          conflicts: [
            {
              moduleIds: ["block.alpha", "block.beta"],
              message: 'File target collision at "src/shared.txt".',
              reason: "Two selected modules write the same file.",
              severity: "error",
            },
          ],
        }),
        outputDir,
        createdAt,
      }),
    ).rejects.toThrow(/Cannot generate project with resolver errors/)
  })

  it("copies a simple template file", async () => {
    const outputDir = await createTempDir("copy-output")
    const templateRoot = await createTempDir("copy-template")

    await mkdir(path.join(templateRoot, "templates"), { recursive: true })
    await writeFile(
      path.join(templateRoot, "templates", "hello.txt"),
      "hello from template\n",
      "utf8",
    )

    const result = await generateProject({
      resolvedRecipe: resolvedRecipe({
        files: [
          {
            from: "templates/hello.txt",
            to: "src/hello.txt",
          },
        ],
      }),
      outputDir,
      templateRoot,
      createdAt,
    })

    await expect(readFile(path.join(outputDir, "src", "hello.txt"), "utf8")).resolves.toBe(
      "hello from template\n",
    )
    expect(result.filesWritten).toContain("src/hello.txt")
  })

  it("fails clearly when a mapped template file is missing", async () => {
    const outputDir = await createTempDir("missing-output")
    const templateRoot = await createTempDir("missing-template")

    await expect(
      generateProject({
        resolvedRecipe: resolvedRecipe({
          files: [
            {
              from: "templates/missing.txt",
              to: "src/missing.txt",
            },
          ],
        }),
        outputDir,
        templateRoot,
        createdAt,
      }),
    ).rejects.toThrow(/Template file "templates\/missing.txt" does not exist/)
  })

  it("does not resolve dependencies internally", async () => {
    const outputDir = await createTempDir("no-resolve-output")
    const templateRoot = await createTempDir("no-resolve-template")

    await mkdir(path.join(templateRoot, "blocks"), { recursive: true })
    await writeFile(
      path.join(templateRoot, "blocks", "navbar.tsx"),
      "export const Navbar = () => null\n",
      "utf8",
    )

    await generateProject({
      resolvedRecipe: resolvedRecipe({
        userSelections: ["block.navbar"],
        effectiveSelections: ["block.navbar"],
        packages: {
          dependencies: {},
          devDependencies: {},
          peerDependencies: {},
        },
        files: [
          {
            from: "blocks/navbar.tsx",
            to: "src/components/blocks/navbar.tsx",
          },
        ],
      }),
      outputDir,
      templateRoot,
      createdAt,
    })

    const packageJson = await readJson<{
      dependencies: Record<string, string>
      devDependencies: Record<string, string>
    }>(path.join(outputDir, "package.json"))

    expect(packageJson.dependencies).toEqual({})
    expect(packageJson.devDependencies).toEqual({})
    await expect(
      exists(path.join(outputDir, "src", "components", "ui", "button.tsx")),
    ).resolves.toBe(false)
    await expect(
      readFile(path.join(outputDir, "src", "components", "blocks", "navbar.tsx"), "utf8"),
    ).resolves.toBe("export const Navbar = () => null\n")
  })
})
