import type { ResolvedRecipe } from "@dittojs/core"

function command(packageManager: string, script: string): string {
  return packageManager === "npm" ? `npm run ${script}` : `${packageManager} ${script}`
}

function stackSummary(resolvedRecipe: ResolvedRecipe): string {
  if (resolvedRecipe.effectiveSelections.length === 0) {
    return "- No stack modules were included."
  }

  return resolvedRecipe.effectiveSelections.map((selection) => `- ${selection}`).join("\n")
}

export function createReadme(input: {
  projectName: string
  packageManager: string
  resolvedRecipe: ResolvedRecipe
}): string {
  const installCommand = `${input.packageManager} install`
  const devCommand = command(input.packageManager, "dev")
  const buildCommand = command(input.packageManager, "build")

  return `# ${input.projectName}

Generated by DittoJs.

## Stack Summary

${stackSummary(input.resolvedRecipe)}

## Commands

Install command:

\`\`\`bash
${installCommand}
\`\`\`

Dev command:

\`\`\`bash
${devCommand}
\`\`\`

Build command:

\`\`\`bash
${buildCommand}
\`\`\`

Generation metadata is stored in \`ditto.generated.json\`.
`
}
