import type { ResolvedRecipe } from "@dittosh/core"

import { GENERATED_NODE_README_REQUIREMENT } from "./node-policy.js"

function command(packageManager: string, script: string): string {
  return packageManager === "npm" ? `npm run ${script}` : `${packageManager} ${script}`
}

function stackSummary(resolvedRecipe: ResolvedRecipe): string {
  if (resolvedRecipe.effectiveSelections.length === 0) {
    return "- No stack modules were included."
  }

  return resolvedRecipe.effectiveSelections.map((selection) => `- ${selection}`).join("\n")
}

function sampleDataSummary(resolvedRecipe: ResolvedRecipe): string {
  const sampleDataSelections = resolvedRecipe.effectiveSelections.filter((selection) =>
    selection.startsWith("sample-data."),
  )

  if (sampleDataSelections.length === 0) {
    return ""
  }

  return `## Mock Data

This template includes mock data modules selected through DittoJs manifests:

${sampleDataSelections.map((selection) => `- ${selection}`).join("\n")}

Mock data is generated under \`src/data/\`. To integrate a backend, replace imports from these files with API calls, server loaders, or your data-fetching client, then remove the corresponding mock data files once no generated page imports them.

`
}

export function createReadme(input: {
  projectName: string
  packageManager: string
  resolvedRecipe: ResolvedRecipe
}): string {
  const installCommand = `${input.packageManager} install`
  const devCommand = command(input.packageManager, "dev")
  const buildCommand = command(input.packageManager, "build")

  return `# ${input.projectName}

Generated by DittoJs.

## Stack Summary

${stackSummary(input.resolvedRecipe)}

## Requirements

- ${GENERATED_NODE_README_REQUIREMENT}

## Commands

Install command:

\`\`\`bash
${installCommand}
\`\`\`

Dev command:

\`\`\`bash
${devCommand}
\`\`\`

Build command:

\`\`\`bash
${buildCommand}
\`\`\`

Generation metadata is stored in \`ditto.generated.json\`.

${sampleDataSummary(input.resolvedRecipe)}
`
}
