import { presetOptions } from "../builder/builder-options"
import { PresetCard } from "../components/builder/preset-card"
import { AppIcon } from "../components/icons"

export function LandingPage({
  onCreatePreset,
  onCustomizePreset,
  onStart,
}: {
  onCreatePreset: (presetId: string) => void
  onCustomizePreset: (presetId: string) => void
  onStart: () => void
}) {
  return (
    <main className="landing-page" id="builder">
      <section className="hero-panel">
        <div className="hero-copy">
          <h1>Generate your next React starter.</h1>
          <p>
            DittoJs creates dependency-correct, customizable React templates with tested defaults,
            smart presets, and clean project structures.
          </p>
          <div className="hero-manifest-preview" aria-label="Manifest preview">
            <span>Preset Manifest</span>
            <strong>React / Vite / Tailwind</strong>
            <small>Generated by resolver</small>
          </div>
          <div className="hero-actions">
            <button type="button" className="button button-dark" onClick={onStart}>
              Start Generating
              <AppIcon name="arrow-right" />
            </button>
            <button type="button" className="button button-light" disabled>
              <AppIcon name="docs" />
              View Docs
            </button>
          </div>
        </div>
      </section>
      <section className="preset-section" aria-labelledby="preset-title">
        <div className="section-heading">
          <h2 id="preset-title">Choose the starting architecture.</h2>
        </div>
        <div className="preset-grid">
          {presetOptions.map((preset) => (
            <PresetCard
              key={preset.id}
              preset={preset}
              onCreate={onCreatePreset}
              onCustomize={onCustomizePreset}
            />
          ))}
        </div>
      </section>
      <footer className="landing-footer">
        <strong>DittoJs</strong>
        <nav aria-label="Footer links">
          <a href="#privacy">Privacy</a>
          <a href="#terms">Terms</a>
          <a href="#support">Support</a>
        </nav>
        <span>© 2024 DittoJs. All rights reserved.</span>
      </footer>
    </main>
  )
}
